#include <vm.h>
#include "opcodes.h"
static const char * opcNames[] = {
	"nop", "aconst_null", "iconst_m1", "iconst_0",
	"iconst_1", "iconst_2", "iconst_3", "iconst_4",
	"iconst_5", "lconst_0", "lconst_1", "fconst_0",
	"fconst_1", "fconst_2", "dconst_0", "dconst_1",
	"bipush", "sipush", "ldc", "ldc_w",
	"ldc2_w", "iload", "lload", "fload",
	"dload", "aload", "iload_0", "iload_1",
	"iload_2", "iload_3", "lload_0", "lload_1",
	"lload_2", "lload_3", "fload_0", "fload_1",
	"fload_2", "fload_3", "dload_0", "dload_1",
	"dload_2", "dload_3", "aload_0", "aload_1",
	"aload_2", "aload_3", "iaload", "laload",
	"faload", "daload", "aaload", "baload",
	"caload", "saload", "istore", "lstore",
	"fstore", "dstore", "astore", "istore_0",
	"istore_1", "istore_2", "istore_3", "lstore_0",
	"lstore_1", "lstore_2", "lstore_3", "fstore_0",
	"fstore_1", "fstore_2", "fstore_3", "dstore_0",
	"dstore_1", "dstore_2", "dstore_3", "astore_0",
	"astore_1", "astore_2", "astore_3", "iastore",
	"lastore", "fastore", "dastore", "aastore",
	"bastore", "castore", "sastore", "pop",
	"pop2", "dup", "dup_x1", "dup_x2",
	"dup2", "dup2_x1", "dup2_x2", "swap",
	"iadd", "ladd", "fadd", "dadd",
	"isub", "lsub", "fsub", "dsub",
	"imul", "lmul", "fmul", "dmul",
	"idiv", "ldiv", "fdiv", "ddiv",
	"irem", "lrem", "frem", "drem",
	"ineg", "lneg", "fneg", "dneg",
	"ishl", "lshl", "ishr", "lshr",
	"iushr", "lushr", "iand", "land",
	"ior", "lor", "ixor", "lxor",
	"iinc", "i2l", "i2f", "i2d",
	"l2i", "l2f", "l2d", "f2i",
	"f2l", "f2d", "d2i", "d2l",
	"d2f", "i2b", "i2c", "i2s",
	"lcmp", "fcmpl", "fcmpg", "dcmpl",
	"dcmpg", "ifeq", "ifne", "iflt",
	"ifge", "ifgt", "ifle", "if_icmpeq",
	"if_icmpne", "if_icmplt", "if_icmpge", "if_icmpgt",
	"if_icmple", "if_acmpeq", "if_acmpne", "goto",
	"jsr", "ret", "tableswitch", "lookupswitch",
	"ireturn", "lreturn", "freturn", "dreturn",
	"areturn", "return", "getstatic", "putstatic",
	"getfield", "putfield", "invokevirtual", "invokespecial",
	"invokestatic", "invokeinterface", "xxxunusedxxx", "new",
	"newarray", "anewarray", "arraylength", "athrow",
	"checkcast", "instanceof", "monitorenter", "monitorexit",
	"wide", "multianewarray", "ifnull", "ifnonnull",
	"goto_w", "jsr_w", "breakpoint", "aldc_ind_quick",
	"aldc_ind_w_quick", "invokestatic_quick", "invokestatic_checkinit_quick", "invokevirtual_quick",
	"getfield_quick", "agetfield_quick", "vinvokevirtual_quick", "invokevirtual_quick_w",
	"putfield_quick", "invokenonvirtual_quick", "invokesuper_quick", "invokeignored_quick",
	"getfield2_quick", "checkcast_quick", "instanceof_quick", "nonnull_quick",
	"putfield2_quick", "ainvokevirtual_quick", "invokevirtualobject_quick", "invokeinterface_quick",
	"aldc_quick", "ldc_quick", "exittransition", "dinvokevirtual_quick",
	"aldc_w_quick", "ldc_w_quick", "aputfield_quick", "getfield_quick_w",
	"ldc2_w_quick", "agetstatic_quick", "getstatic_quick", "getstatic2_quick",
	"aputstatic_quick", "putstatic_quick", "putstatic2_quick", "agetstatic_checkinit_quick",
	"getstatic_checkinit_quick", "getstatic2_checkinit_quick", "aputstatic_checkinit_quick", "putstatic_checkinit_quick",
	"putstatic2_checkinit_quick", "putfield_quick_w", "new_checkinit_quick", "new_quick",
	"anewarray_quick", "multianewarray_quick", "prefix", "invokeinit",
	"??252", "??253", "hardware", "software",
};

const char opcodeLengths[256] = {
	1,    /* opc_nop */
	1,    /* opc_aconst_null */
	1,    /* opc_iconst_m1 */
	1,    /* opc_iconst_0 */
	1,    /* opc_iconst_1 */
	1,    /* opc_iconst_2 */
	1,    /* opc_iconst_3 */
	1,    /* opc_iconst_4 */
	1,    /* opc_iconst_5 */
	1,    /* opc_lconst_0 */
	1,    /* opc_lconst_1 */
	1,    /* opc_fconst_0 */
	1,    /* opc_fconst_1 */
	1,    /* opc_fconst_2 */
	1,    /* opc_dconst_0 */
	1,    /* opc_dconst_1 */
	2,    /* opc_bipush */
	3,    /* opc_sipush */
	2,    /* opc_ldc */
	3,    /* opc_ldc_w */
	3,    /* opc_ldc2_w */
	2,    /* opc_iload */
	2,    /* opc_lload */
	2,    /* opc_fload */
	2,    /* opc_dload */
	2,    /* opc_aload */
	1,    /* opc_iload_0 */
	1,    /* opc_iload_1 */
	1,    /* opc_iload_2 */
	1,    /* opc_iload_3 */
	1,    /* opc_lload_0 */
	1,    /* opc_lload_1 */
	1,    /* opc_lload_2 */
	1,    /* opc_lload_3 */
	1,    /* opc_fload_0 */
	1,    /* opc_fload_1 */
	1,    /* opc_fload_2 */
	1,    /* opc_fload_3 */
	1,    /* opc_dload_0 */
	1,    /* opc_dload_1 */
	1,    /* opc_dload_2 */
	1,    /* opc_dload_3 */
	1,    /* opc_aload_0 */
	1,    /* opc_aload_1 */
	1,    /* opc_aload_2 */
	1,    /* opc_aload_3 */
	1,    /* opc_iaload */
	1,    /* opc_laload */
	1,    /* opc_faload */
	1,    /* opc_daload */
	1,    /* opc_aaload */
	1,    /* opc_baload */
	1,    /* opc_caload */
	1,    /* opc_saload */
	2,    /* opc_istore */
	2,    /* opc_lstore */
	2,    /* opc_fstore */
	2,    /* opc_dstore */
	2,    /* opc_astore */
	1,    /* opc_istore_0 */
	1,    /* opc_istore_1 */
	1,    /* opc_istore_2 */
	1,    /* opc_istore_3 */
	1,    /* opc_lstore_0 */
	1,    /* opc_lstore_1 */
	1,    /* opc_lstore_2 */
	1,    /* opc_lstore_3 */
	1,    /* opc_fstore_0 */
	1,    /* opc_fstore_1 */
	1,    /* opc_fstore_2 */
	1,    /* opc_fstore_3 */
	1,    /* opc_dstore_0 */
	1,    /* opc_dstore_1 */
	1,    /* opc_dstore_2 */
	1,    /* opc_dstore_3 */
	1,    /* opc_astore_0 */
	1,    /* opc_astore_1 */
	1,    /* opc_astore_2 */
	1,    /* opc_astore_3 */
	1,    /* opc_iastore */
	1,    /* opc_lastore */
	1,    /* opc_fastore */
	1,    /* opc_dastore */
	1,    /* opc_aastore */
	1,    /* opc_bastore */
	1,    /* opc_castore */
	1,    /* opc_sastore */
	1,    /* opc_pop */
	1,    /* opc_pop2 */
	1,    /* opc_dup */
	1,    /* opc_dup_x1 */
	1,    /* opc_dup_x2 */
	1,    /* opc_dup2 */
	1,    /* opc_dup2_x1 */
	1,    /* opc_dup2_x2 */
	1,    /* opc_swap */
	1,    /* opc_iadd */
	1,    /* opc_ladd */
	1,    /* opc_fadd */
	1,    /* opc_dadd */
	1,    /* opc_isub */
	1,    /* opc_lsub */
	1,    /* opc_fsub */
	1,    /* opc_dsub */
	1,    /* opc_imul */
	1,    /* opc_lmul */
	1,    /* opc_fmul */
	1,    /* opc_dmul */
	1,    /* opc_idiv */
	1,    /* opc_ldiv */
	1,    /* opc_fdiv */
	1,    /* opc_ddiv */
	1,    /* opc_irem */
	1,    /* opc_lrem */
	1,    /* opc_frem */
	1,    /* opc_drem */
	1,    /* opc_ineg */
	1,    /* opc_lneg */
	1,    /* opc_fneg */
	1,    /* opc_dneg */
	1,    /* opc_ishl */
	1,    /* opc_lshl */
	1,    /* opc_ishr */
	1,    /* opc_lshr */
	1,    /* opc_iushr */
	1,    /* opc_lushr */
	1,    /* opc_iand */
	1,    /* opc_land */
	1,    /* opc_ior */
	1,    /* opc_lor */
	1,    /* opc_ixor */
	1,    /* opc_lxor */
	3,    /* opc_iinc */
	1,    /* opc_i2l */
	1,    /* opc_i2f */
	1,    /* opc_i2d */
	1,    /* opc_l2i */
	1,    /* opc_l2f */
	1,    /* opc_l2d */
	1,    /* opc_f2i */
	1,    /* opc_f2l */
	1,    /* opc_f2d */
	1,    /* opc_d2i */
	1,    /* opc_d2l */
	1,    /* opc_d2f */
	1,    /* opc_i2b */
	1,    /* opc_i2c */
	1,    /* opc_i2s */
	1,    /* opc_lcmp */
	1,    /* opc_fcmpl */
	1,    /* opc_fcmpg */
	1,    /* opc_dcmpl */
	1,    /* opc_dcmpg */
	3,    /* opc_ifeq */
	3,    /* opc_ifne */
	3,    /* opc_iflt */
	3,    /* opc_ifge */
	3,    /* opc_ifgt */
	3,    /* opc_ifle */
	3,    /* opc_if_icmpeq */
	3,    /* opc_if_icmpne */
	3,    /* opc_if_icmplt */
	3,    /* opc_if_icmpge */
	3,    /* opc_if_icmpgt */
	3,    /* opc_if_icmple */
	3,    /* opc_if_acmpeq */
	3,    /* opc_if_acmpne */
	3,    /* opc_goto */
	3,    /* opc_jsr */
	2,    /* opc_ret */
	0,    /* opc_tableswitch */
	0,    /* opc_lookupswitch */
	1,    /* opc_ireturn */
	1,    /* opc_lreturn */
	1,    /* opc_freturn */
	1,    /* opc_dreturn */
	1,    /* opc_areturn */
	1,    /* opc_return */
	3,    /* opc_getstatic */
	3,    /* opc_putstatic */
	3,    /* opc_getfield */
	3,    /* opc_putfield */
	3,    /* opc_invokevirtual */
	3,    /* opc_invokespecial */
	3,    /* opc_invokestatic */
	5,    /* opc_invokeinterface */
	0,    /* opc_xxxunusedxxx */
	3,    /* opc_new */
	2,    /* opc_newarray */
	3,    /* opc_anewarray */
	1,    /* opc_arraylength */
	1,    /* opc_athrow */
	3,    /* opc_checkcast */
	3,    /* opc_instanceof */
	1,    /* opc_monitorenter */
	1,    /* opc_monitorexit */
	0,    /* opc_wide */
	4,    /* opc_multianewarray */
	3,    /* opc_ifnull */
	3,    /* opc_ifnonnull */
	5,    /* opc_goto_w */
	5,    /* opc_jsr_w */
	1,    /* opc_breakpoint */
	2,    /* opc_aldc_ind_quick */
	3,    /* opc_aldc_ind_w_quick */
	3,    /* opc_invokestatic_quick */
	3,    /* opc_invokestatic_checkinit_quick */
	3,    /* opc_invokevirtual_quick */
	3,    /* opc_getfield_quick */
	3,    /* opc_agetfield_quick */
	3,    /* opc_vinvokevirtual_quick */
	3,    /* opc_invokevirtual_quick_w */
	3,    /* opc_putfield_quick */
	3,    /* opc_invokenonvirtual_quick */
	3,    /* opc_invokesuper_quick */
	3,    /* opc_invokeignored_quick */
	3,    /* opc_getfield2_quick */
	3,    /* opc_checkcast_quick */
	3,    /* opc_instanceof_quick */
	1,    /* opc_nonnull_quick */
	3,    /* opc_putfield2_quick */
	3,    /* opc_ainvokevirtual_quick */
	3,    /* opc_invokevirtualobject_quick */
	5,    /* opc_invokeinterface_quick */
	2,    /* opc_aldc_quick */
	2,    /* opc_ldc_quick */
	1,    /* opc_exittransition */
	3,    /* opc_dinvokevirtual_quick */
	3,    /* opc_aldc_w_quick */
	3,    /* opc_ldc_w_quick */
	3,    /* opc_aputfield_quick */
	3,    /* opc_getfield_quick_w */
	3,    /* opc_ldc2_w_quick */
	3,    /* opc_agetstatic_quick */
	3,    /* opc_getstatic_quick */
	3,    /* opc_getstatic2_quick */
	3,    /* opc_aputstatic_quick */
	3,    /* opc_putstatic_quick */
	3,    /* opc_putstatic2_quick */
	3,    /* opc_agetstatic_checkinit_quick */
	3,    /* opc_getstatic_checkinit_quick */
	3,    /* opc_getstatic2_checkinit_quick */
	3,    /* opc_aputstatic_checkinit_quick */
	3,    /* opc_putstatic_checkinit_quick */
	3,    /* opc_putstatic2_checkinit_quick */
	3,    /* opc_putfield_quick_w */
	3,    /* opc_new_checkinit_quick */
	3,    /* opc_new_quick */
	3,    /* opc_anewarray_quick */
	4,    /* opc_multianewarray_quick */
	0,    /* opc_prefix */
	3,    /* opc_invokeinit */
	0,
	0,
	0,
	0,
};

uint8_t opcodeLen(uint8_t opcode)
{
	return opcodeLengths[opcode];
}

const char * opcodeName(uint8_t opcode)
{
	return opcNames[opcode];
}